import React from 'react';
import type { AppProps } from 'next/app';
import '../styles/globals.css';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return <>
        <Head>
            <title>MyTop - наш лучший топ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            {/* <link rel="preconnect" href="https://fonts.gstatic.com" /> */}
            {/* <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap" rel="stylesheet" /> */}
        </Head>
      <Component {...pageProps} />
   </>;
}
